name: Sadık Ay
description: A bit software, a bit travel and completely freedom.

url: http://sadikay.github.com.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact